[package]
name = "halton"
version = "0.1.0"
authors = ["Mat Sadler <mat@sourcetagsandcodes.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
halton = "0.2.1"
lazy_static = "1"
magnus = "0.1.0"
