name: Gem

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  native:
    name: Build native gems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-platform:
        - x86_64-linux
        - x86_64-linux-musl
        - aarch64-linux
        - x86_64-darwin
        - arm64-darwin
        - x64-mingw32
        - x64-mingw-ucrt
    steps:
    - uses: actions/checkout@v3

    - uses: oxidize-rb/actions/setup-ruby-and-rust@main
      with:
        ruby-version: "3.2"
        bundler-cache: false
        cargo-cache: true
        cargo-vendor: true
        cache-version: v0-${{ matrix.ruby-platform }}

    - uses: oxidize-rb/cross-gem-action@main
      with:
        platform: ${{ matrix.ruby-platform }}
        ruby-versions: "2.6, 2.7, 3.0, 3.1, 3.2"
        setup: |
          ruby -e 'exit Gem::Version.new(Gem::VERSION) < "3.3.26" ? 0 : 1' && gem update --system 3.3.26
          bundle
