name: Test

on:
- push
- pull_request

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        ruby-version:
        - "2.6"
        - "2.7"
        - "3.0"
        - "3.1"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Set up Rust
      if: matrix.os == 'windows-latest'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-x86_64-pc-windows-gnu
        default: true
    - name: Run tests
      run: rake test
